config/routes.rb
Rails.application.routes.draw do
  resources :tests, only: %i[index]
  resources :unprocessed_images, only: %i[create show edit update]
  resource :my_page, only: :show

  match "/auth/:provider/callback", to: "sessions#create", via: %i[get post]
  delete "/auth", to: "sessions#destroy"

  root to: "tops#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ip_location.rb
class IpLocation < ApplicationRecord
  FALLBACK_LAT = 0
  FALLBACL_LNG = 0

  before_create :set_lat_lng

  def self.by_ip(ip)
    find_or_create_by(ip: ip).to_lat_lng
  end

  def to_lat_lng
    set_lat_lng && save! if cache_to_old?
    { lat: lat, lng: lng }
  end

  private

  def cache_to_old?
    updated_at < 1.day.ago
  end

  def set_lat_lng
    lat, lng = Geocoder.search(ip.to_s).first&.coordinates

    assign_attributes(lat: lat || FALLBACK_LAT, lng: lng || FALLBACL_LNG)
  end
end

app/models/unprocessed_image.rb
class UnprocessedImage < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  scope :with_user, ->(user) { where(user: user) }

  def processed?
    position_processed?
  end

  def process_later
    ImageLocationDetectionJob.perform_later(id)
  end

  def process
    update!(lat_lng.merge(position_processed: true))
  end

  private

  def lat_lng
    image.open do |file|
      data = Exif::Data.new(file)

      if data.gps_latitude && data.gps_longitude
        {
          lat: rational_coordinate_to_decimal(data.gps_latitude),
          lng: rational_coordinate_to_decimal(data.gps_longitude),
        }
      else
        IpLocation.by_ip(uploader_ip)
      end
    end
  rescue Exif::NotReadable
    IpLocation.by_ip(uploader_ip)
  end

  def rational_coordinate_to_decimal(coordinate)
    degrees, minutes, seconds = coordinate
    (degrees + minutes / 60 + seconds / 3_600).to_f
  end
end

app/models/user.rb
class User < ApplicationRecord
  PROVIDER = %w[developer github].freeze

  has_many :unprocessed_images,
           -> { order(created_at: :desc) },
           dependent: :destroy, inverse_of: :user

  def self.find_or_create_from_auth_hash(auth_hash)
    user_id, provider = auth_hash.values_at :uid, :provider

    find_or_initialize_by(user_id: user_id, provider: provider).tap do |user|
      name, email = auth_hash.info.values_at :name, :email
      user.email = email
      user.name = name
      user.save!
    end
  end

  validates :user_id, :name, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :provider, inclusion: { in: PROVIDER }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :redirect_when_unauthorized
  helper_method :current_user

  private

  def current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  def redirect_when_unauthorized
    redirect_to root_url unless current_user
  end
end

app/controllers/my_pages_controller.rb
class MyPagesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :create
  skip_before_action :redirect_when_unauthorized, only: :create

  def create
    user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = user.id

    redirect_to my_page_path
  end

  def destroy
    message = "Until next time #{current_user.name}."
    session[:user_id] = nil

    redirect_to root_path, notice: message
  end

  private

  def auth_hash
    request.env["omniauth.auth"]
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  skip_before_action :redirect_when_unauthorized, only: :index

  def index; end
end

app/controllers/unprocessed_images_controller.rb
class UnprocessedImagesController < ApplicationController
  def show
    render partial: UnprocessedImage.with_user(current_user).find(params[:id])
  end

  def create
    image = UnprocessedImage.create(unprocessed_image_params)
    image.process_later
    render partial: image
  end

  def edit
    render "update", layout: false
  end

  private

  def unprocessed_image_params
    params.require(:unprocessed_image).permit(:image).merge(
      user: current_user, uploader_ip: request.remote_ip,
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def github_auth_path
    "#{auth_path}/#{:github}"
  end

  def developer_auth_path
    "#{auth_path}/#{:developer}"
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end

  def bootstrap_class_for_flash(flash_type)
    case flash_type
    when "success"
      "alert-success"
    when "error"
      "alert-danger"
    when "alert"
      "alert-warning"
    when "notice"
      "alert-info"
    else
      flash_type.to_s
    end
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="4.0.0";
    analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    analytics.page();
    }}();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="container">
    <% user_facing_flashes.each do |type, message| -%>
      <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show"
           data-controller="flash" role="alert">
        <%= message %>
        <button class="close" data-action="flash#close">x</button>
      </div>
    <% end -%>
  </div>
<% end %>

app/views/application/_modal.html.erb
<div class="modal fade"
     tabindex="-1"
     role="dialog"
     aria-labelledby="modal"
     aria-hidden="true"
     data-controller="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content" data-target="modal.content"></div>
  </div>
</div>

app/views/application/_navigation.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to "My Journey", root_path, class: "navbar-brand" %>

  <ul class="nav d-flex align-items-center">
    <% if current_user %>
      <li class="nav-item dropdown" data-controller="dropdown">
        <a class="nav-link dropdown-toggle"
           href="#"
           role="button"
           data-action="dropdown#toggle"
           aria-haspopup="true"
           aria-expanded="false">
          <%= inline_svg "@fortawesome/fontawesome-free/svgs/solid/user.svg", class: "nav-icon" %>
          <span class="navbar-text">
            <%= current_user.name %>
          </span>
        </a>
        <div class="dropdown-menu"
             aria-labelledby="navbarDropdownMenuLink"
             data-target="dropdown.menu">
          <%= button_to "Sign Out!", auth_path, class: "dropdown-item",
                                                method: :delete,
                                                data: { target: "dropdown.item" } %>
        </div>
      </li>
    <% else %>
      <li class="nav-item">
        <span class="navbar-text">
          Sign in with
        </span>
        <%= button_to github_auth_path, class: "btn btn-link btn-sm" do %>
          <span class="sr-only">Github</span>
          <%= inline_svg "@fortawesome/fontawesome-free/svgs/brands/github.svg", class: "nav-icon" %>
        <% end %>
        <% unless Rails.env.production? %>
          <%= button_to developer_auth_path, class: "btn btn-link btn-sm" do %>
            <%= inline_svg "@fortawesome/fontawesome-free/svgs/brands/dev.svg", class: "nav-icon" %>
          <% end %>
        <% end %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, integrity: true, media: "all", "data-turbolinks-track": "reload" %>
  <%= javascript_pack_tag :application, integrity: true, "data-turbolinks-track": "reload", defer: true %>

  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "modal" %>
  <%= render "navigation" %>
  <%= render "flashes" -%>
  <%= yield %>
  <%= render "css_overrides" %>
</body>
</html>

app/views/my_pages/show.html.erb
<main class="container">
  <h1>Explore your journey around the world.</h1>

  <section data-controller="upload" data-upload-url="<%= rails_direct_uploads_path %>">
    <template data-target="upload.template">
      <div class="drop-zone__item">
        <img class="drop-zone__item__image" src="IMAGE_URL">
        <%= inline_svg "@fortawesome/fontawesome-free/svgs/solid/spinner.svg", class: "drop-zone__item__icon drop-zone__item__state--downloading" %>
        <%= inline_svg "@fortawesome/fontawesome-free/svgs/solid/check-double.svg", class: "drop-zone__item__icon drop-zone__item__state--downloaded" %>
      </div>
    </template>

    <%= tag.div class: "drop-zone", id: "drop-zone", data: {
      target: "upload.dropZone",
      action: [
        "click->upload#open",
        "dragover->upload#dragOver",
        "dragleave->upload#dragLeave",
        "dragenter->upload#dragEnter",
        "drop->upload#drop",
      ].join(" "),
    } %>

    <%= form_with(model: UnprocessedImage.new, data: { target: "upload.form", action: "ajax:success->upload#show" }) do |form| %>
      <%= form.hidden_field :image, data: { target: "upload.fileInput" } %>
    <% end %>

    <%= file_field_tag :files, multiple: true, hidden: true, data: { action: "change->upload#save", target: "upload.input" } %>

    <div id="unprocessed-images" class="card-columns" data-target="upload.uploads">
      <% current_user.unprocessed_images.each do |unprocessed_image| %>
        <%= render unprocessed_image %>
      <% end %>
    </div>
  </section>
</main>

app/views/unprocessed_images/_unprocessed_image.html.erb
<div class="card bg-dark"
     data-controller="unprocessed-image"
     data-unprocessed-image-processing="<%= !unprocessed_image.processed? %>"
     data-unprocessed-image-url="<%= unprocessed_image_path(unprocessed_image.id) %>">
  <%= image_tag unprocessed_image.image.variant({ thumbnail: "530x" }), class: "card-img" %>
  <div class="card-img-overlay d-flex justify-content-center align-items-end">
    <div class="w-100 d-flex flex-column">
      <% if unprocessed_image.processed? %>
        <%= link_to "Save to journey", edit_unprocessed_image_path(unprocessed_image),
          class: "btn btn-primary btn-block",
          data: { remote: true, action: "ajax:success->unprocessed-image#edit" } %>
      <% else %>
        <div class="progress">
          <div class="progress-bar progress-bar-striped progress-bar-animated"
               role="progressbar"
               style="width: 25%"
               aria-valuenow="10"
               aria-valuemin="0"
               aria-valuemax="100"
               data-target="unprocessed-image.progress">
          </div>
        </div>
      <% end %>
    </div>
    <%
      # <div class="embed-responsive embed-responsive-16by9">
      #   <div class="embed-responsive-item" data-target="unprocessed-image.map">
      #   </div>
      # </div>
      %>
  </div>
</div>

app/views/unprocessed_images/update.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
  <button type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
          data-controller="modal-closer"
          data-action="modal-closer#close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
  Hoge Moge
</div>
<div class="modal-footer">
  <button type="button"
          class="btn btn-secondary"
          data-controller="modal-closer"
          data-action="modal-closer#close">
    Close
  </button>
  <button type="button" class="btn btn-primary">Save changes</button>
</div>